--- #YAML:1.0
name:               Algorithm-TicketClusterer
version:            1.0
abstract:           A Perl Module for Retrieving Tickets Similar to a Given Ticket
author:
    - Avinash Kak (kak@purdue.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Spreadsheet::ParseExcel:  0.59
    Spreadsheet::XLSX:    0.13
    WordNet::QueryData:   1.49
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
