---
abstract: 'A Perl Module for Retrieving Tickets Similar to a Given Ticket'
author:
  - 'Avinash Kak (kak@purdue.edu)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-TicketClusterer
no_index:
  directory:
    - t
    - inc
requires:
  Spreadsheet::ParseExcel: 0.59
  Spreadsheet::XLSX: 0.13
  Text::Iconv: 1.7
  WordNet::QueryData: 1.47
version: 1.01
